per_page: 15
exams:
  status:
    start: "start"
    uncheck: "uncheck"
    checked: "checked"
    testing: "testing"
  duration: 20
  question_number: 30
  time_minute: 60
  time_out: 0
  one: 1
question:
  type:
    single: "single"
    multiple: "multiple"
    text: "text"
  status:
    waiting: "waiting"
    approved: "approved"
